### ISSUE TITLE
Winners quote

### ISSUE THREAD

**Issue by PatrickAlphaC** [apronotti/2fa-for-smartcontracts#1]
Hi team!

Congratulations on winner the judge's pick for the hackathon! I'd love to connect to get a quote from you guys to share it on our blog and give your project a little extra love. Are you all on discord?

**Comment by PatrickAlphaC** [comment]
https://discord.gg/2YHSAey

**Comment by apronotti** [comment]
> Hi team!
> 
> Congratulations on winner the judge's pick for the hackathon! I'd love to connect to get a quote from you guys to share it on our blog and give your project a little extra love. Are you all on discord?

Hi, Patrick. It's an honor to have participated in this hackathon, thanks for the help and the opportunity to add value to the great chainlink project.

Our discord's names are mhepp#6975 , Javier#7831 , apronotti#2919.

**Comment by PatrickAlphaC** [comment]
Sent, I'll talk to your team soon!
